version: '3'

services:
  db-1:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: food_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
  
  www:
    depends_on:
      - db-1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lamp-docker

  phpmyadmin:
    depends_on:
      - db-1
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db-1
      PMA_PORT: 3306
    networks:
      - lamp-docker

networks:
  lamp-docker:
    driver: bridge
